### ISSUE TITLE
Unable to use server

### ISSUE THREAD

**Issue by EPNW-Eric** [speechcatcher-asr/speechcatcher#13]
Hi,

when running
```bash
root@a6b96eee2850:/mnt# speechcatcher_server --port 2700 --cache-dir /models --device cuda --host 0.0.0.0
```
I get the following error:
```bash
Loading model pool: speechcatcher/speechcatcher_german_espnet_streaming_transformer_26k_train_size_xl_raw_de_bpe1024
Load instance: 1
Load instance: 2
Load instance: 3
Load instance: 4
Load instance: 5
Load instance: 6
Load instance: 7
Load instance: 8
Starting WebSocket server on ws://0.0.0.0:2700
ERROR:websockets.server:connection handler failed
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/websockets/asyncio/server.py", line 376, in conn_handler
    await self.handler(connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: start_server.<locals>.<lambda>() missing 1 required positional argument: 'path'
ERROR:websockets.server:connection handler failed
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/websockets/asyncio/server.py", line 376, in conn_handler
    await self.handler(connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: start_server.<locals>.<lambda>() missing 1 required positional argument: 'path'
```

I am using this container to execute it, `speechcatcher` (without server) works just fine:
```Dockerfile
FROM nvidia/cuda:13.0.0-cudnn-devel-ubuntu24.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
		portaudio19-dev \
		python3.12 \
		python3.12-dev \
		python3-pip \
		python3-venv \
		ffmpeg \
		libhdf5-dev \
		git \
		git-lfs \
		build-essential \
		nano \
		wget \
	&& rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip && \
	pip install git+https://github.com/speechcatcher-asr/speechcatcher

CMD ["speechcatcher_server","--vosk-output-format","--port","2700","--host","0.0.0.0","--cache-dir","/models","--device","cuda"]
```

**Comment by EPNW-Eric** [comment]
Ok, I found the issue:
The current (as of 20.08.2025) version of `websockets` (`15`) is incompatible, so I downgraded manually:

```bash
pip uninstall websockets
pip install "websockets<11"
```

Would you mind either upgrading your code to work with the latest dependencies or restrict the versions in the `requirements.txt`?

**Comment by bmilde** [comment]
Thanks for reporting! Works on my end (Mac OS X though) with 15.0:

```
(speechcatcher_venv) me@mini4 speechcatcher % pip uninstall websockets
Found existing installation: websockets 15.0.1
Uninstalling websockets-15.0.1:
  Would remove:
    /Volumes/srv/projects/speechcatcher/speechcatcher_venv/bin/websockets
    /Volumes/srv/projects/speechcatcher/speechcatcher_venv/lib/python3.13/site-packages/websockets-15.0.1.dist-info/*
    /Volumes/srv/projects/speechcatcher/speechcatcher_venv/lib/python3.13/site-packages/websockets/*
Proceed (Y/n)? Y
  Successfully uninstalled websockets-15.0.1
(speechcatcher_venv) me@mini4 speechcatcher % pip install websockets
Collecting websockets
  Using cached websockets-15.0.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.8 kB)
Using cached websockets-15.0.1-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Installing collected packages: websockets
Successfully installed websockets-15.0.1

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
(speechcatcher_venv) me@mini4 speechcatcher % speechcatcher_server
Loading model pool: speechcatcher/speechcatcher_german_espnet_streaming_transformer_26k_train_size_xl_raw_de_bpe1024
Load instance: 1
Load instance: 2
Load instance: 3
Load instance: 4
Load instance: 5
Load instance: 6
Load instance: 7
Load instance: 8
Starting WebSocket server on ws://localhost:2700

```

Will try this on Linux too. I'd prefer a fix that would make this work with old and new versions of the websocket library if that's really the issue here.

**Comment by bmilde** [comment]
Gottcha, I was able to replicate this. Similar error here: https://stackoverflow.com/questions/79361897/websocket-error-connection-handler-failed

This has to do with the rewrite of the asyncio implementation in the websockets library:

> With the new asyncio implementation of the websockets library, the path argument of connection handlers is "unnecessary since 10.1 and deprecated in 13.0" ([read here](https://websockets.readthedocs.io/en/stable/howto/upgrade.html)).

I'll fix this so that speechcatcher works with the rewritten asyncio implementation.

**Comment by bmilde** [comment]
Fixed in https://github.com/speechcatcher-asr/speechcatcher/commit/6791e0ab7af8f2b4655350f993d725c2c2378235

You will need to upgrade websockets again, the current code should work with >=14.0. I used 15.0 and python3.13 to test this.

Please let me know if this fix works for you as well!
